### PR TITLE
test: skip non-grammar optional-dependency tests on a base install and add a base-install CI job (#1410)

### LINKED ISSUE #1410: test: non-grammar optional-dependency tests fail instead of skipping on a base [test] install
## Problem

Follow-up to #1371, which covers optional tree-sitter grammars. Running the unit suite on a base install (`uv pip install -e '.[test]'`, no other extras) also fails tests whose missing dependency is not a grammar:

- `test_unixcoder_unit.py`: collection ImportError (needs the `semantic` extra).
- `test_vector_store.py::test_clear_all_embeddings_qdrant_drops_and_recreates_collection`: `AttributeError: 'NoneType' object has no attribute 'COSINE'` at vector_store.py:355 because the guarded qdrant-client import left `models` as None.
- `test_cli_smoke.py` help tests fail due to #1409 (a product bug, tracked separately).
- `test_cgr_shim.py::TestCgrShimExports::test_all_matches_module_exports` failed once under xdist on the base install but passes standalone; likely import-order dependent, needs a look.

## Expected

Same principle as #1371: tests gated on an optional dependency should `pytest.importorskip`/skip with a clear reason on a base install, so the suite is green with skips.

## Suggested follow-through

Once this and #1409 land, add the CI job #1371 suggests (unit suite on a base install) so green-with-skips stays enforced.

### PR DESCRIPTION
**Pull request by vitali87**
## Summary

- The remaining base-install test failures whose missing dependency is not a tree-sitter grammar now skip with a clear reason: `test_unixcoder_unit` importorskips torch (semantic extra), the qdrant clear-all test gets the file's existing `has_qdrant_client` skipif marker, and the cgr shim export test compares identifier names only, since pytest's assertion rewriting injects `@py_builtins`/`@pytest_ar` into the module depending on import order.
- A new `Unit Tests (base install)` CI job (`uv sync --extra test --group dev`, then the unit suite) enforces green-with-skips on a base install from now on, wired into `All Checks Pass`.

## Type of Change

- [x] Bug fix
- [x] CI/CD or tooling

## Related Issues

Fixes #1410. Builds on #1371 (grammar skips, merged in #1411). The `cgr help` failures the same reproduction surfaced are a product bug with typer >= 0.22, fixed separately in #1412; they cannot reach the new CI job because it resolves from uv.lock (typer 0.21.1).

## Test Plan

- [x] Unit tests pass (`make test-parallel` or `uv run pytest -n auto -m "not integration"`)
- [x] Manual testing (describe below)

Full install: the three touched files pass (58 tests). Base install (`uv pip install -e ".[test]"` venv): the whole unit suite now reports 3 failed, 4767 passed, 3092 skipped, where the 3 failures are exactly the typer 0.27 help bugs tracked in #1412 and do not affect the lock-based CI job.

## Checklist

- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format
- [x] All pre-commit checks pass (`make pre-commit`)
- [x] No hardcoded strings in non-config/non-constants files
- [x] No `# type: ignore`, `cast()`, `Any`, or `object` type hints
- [x] No new comments or docstrings (code should be self-documenting)

## Summary by CodeRabbit

- **Tests**
  - Improved test reliability when optional dependencies are unavailable by skipping affected tests instead of failing during collection.
  - Refined public API checks to ignore internal testing attributes.
  - Added coverage for non-integration unit tests in the continuous integration process.
  - Ensured the overall validation check reports failure when unit tests do not pass.
  - Preserved failure visibility for defects in core functionality while handling unavailable optional components gracefully.
  - Avoided unnecessary model downloads for test jobs that do not use semantic features.

### CODE REVIEW

**Comment by vitali87** [comment]
@greptile review

**Comment by vitali87** [comment]
@greptile review

File: .github/workflows/ci.yml [hunk 1]
```diff
@@ -168,6 +168,40 @@ jobs:
...
+    # or milvus. Grammar- and optional-dependency-gated tests must SKIP here,
+    # not fail (issues #1371 and #1410); this job keeps that enforced.
+    timeout-minutes: 30
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          submodules: recursive
+          fetch-depth: 0
```
[the remark this answers is not in the document]
Comment (vitali87) [reply .github/workflows/ci.yml:184]: Added in the follow-up commit: the base-install job's checkout now sets persist-credentials: false, matching the existing hardened checkout in this workflow.

**Comment by vitali87** [comment]
@greptile review
