### ISSUE TITLE
test: non-grammar optional-dependency tests fail instead of skipping on a base [test] install

### ISSUE THREAD

**Issue by vitali87** [vitali87/code-graph-rag#1410]
## Problem

Follow-up to #1371, which covers optional tree-sitter grammars. Running the unit suite on a base install (`uv pip install -e '.[test]'`, no other extras) also fails tests whose missing dependency is not a grammar:

- `test_unixcoder_unit.py`: collection ImportError (needs the `semantic` extra).
- `test_vector_store.py::test_clear_all_embeddings_qdrant_drops_and_recreates_collection`: `AttributeError: 'NoneType' object has no attribute 'COSINE'` at vector_store.py:355 because the guarded qdrant-client import left `models` as None.
- `test_cli_smoke.py` help tests fail due to #1409 (a product bug, tracked separately).
- `test_cgr_shim.py::TestCgrShimExports::test_all_matches_module_exports` failed once under xdist on the base install but passes standalone; likely import-order dependent, needs a look.

## Expected

Same principle as #1371: tests gated on an optional dependency should `pytest.importorskip`/skip with a clear reason on a base install, so the suite is green with skips.

## Suggested follow-through

Once this and #1409 land, add the CI job #1371 suggests (unit suite on a base install) so green-with-skips stays enforced.
